### ISSUE TITLE
Install with composer not available

### ISSUE THREAD

**Issue by pdenissen** [CCV/ccvonlinepayments-magento2#1]
Hi there,

According the installation manual of CCV it should be possible to install the extension with Composer.
https://www.ccv.eu/nl/wp-content/uploads/sites/7/2021/02/Magento-Webshop-koppelen-aan-CCV-Online-Payments.pdf

When I try to install it with: `composer require ccvonlinepayments/magento2` it gives me the error:
`Could not find a matching version of package ccvonlinepayments/magento2. Check the package spelling, your version constraint and that the package is available in a stability
   which matches your minimum-stability (stable).`

I prefer to install Magento extensions with composer and not in `app/code`.

I hope you can help me out on this.

**Comment by dieterlambrecht** [comment]
Hello

First of all: thank you for your feedback! We're currently investigating the issue. We'll get back to you as soon as we know more.

Best regards

**Comment by dieterlambrecht** [comment]
I'm happy to report we've found the issue. All packages should now be available and accessible on Packagist under `ccv/magento2`. The manual is being updated right now.

In the meantime, you can already use the following commands to install the plugin:
```
composer require ccv/magento2
bin/magento module:enable --clear-static-content CCVOnlinePayments_Magento
bin/magento setup:upgrade
bin/magento cache:clean
```

**Comment by pdenissen** [comment]
Hi @dieterlambrecht ,
Thanks for picking this up. Unfortunately my client has decided to go with another PSP. So I've installed another plugin.
I hope new customers can now install the CCV plugin.
Thanks for solving this.
